export const applicationEmailTemplates = [
  {
    id: 'ownership-code',
    label: 'Verify',
    tone: 'Trust check',
    status: 'Sent during verification',
    subject: 'Your Raptive Community verification code',
    previewText: 'Use this code to confirm the creator account tied to your application.',
    heading: 'Confirm it is really you.',
    body: [
      'We received your Raptive Community application draft for Culture Crave.',
      'Enter the code below to confirm that you control the creator account or domain connected to this application.',
      'This verification keeps the review process focused on your real creator presence and protects your audience from impersonation.',
    ],
    code: 'CULTURE-453',
    primaryAction: {
      label: 'Continue verification',
      href: 'https://community-ds.vercel.app/community-ds/?view=creator-application-page',
    },
    secondaryNote: 'This code expires in 20 minutes. Raptive will never ask for your password.',
  },
  {
    id: 'review-draft',
    label: 'Review',
    tone: 'Resume flow',
    status: 'Sent if the creator pauses before submission',
    subject: 'Your community application draft is ready to review',
    previewText: 'We found your creator details and saved the community preview for you.',
    heading: 'Take a look at what we found.',
    body: [
      'We used your submitted creator link to prepare an application draft with your public profile, audience signals, brand colors, and a proposed community preview.',
      'Please review the details before submission. You can remove anything that looks wrong or correct the fields that need a closer touch.',
      'Nothing has been submitted for approval until you finish verification and agree to the Community Terms.',
    ],
    primaryAction: {
      label: 'Review my draft',
      href: 'https://community-ds.vercel.app/community-ds/?view=creator-application-page',
    },
    secondaryNote: 'Estimated time remaining: about 2 minutes.',
  },
  {
    id: 'submitted',
    label: 'Submitted',
    tone: 'Confirmation',
    status: 'Sent immediately after application submission',
    subject: 'We received your Raptive Community application',
    previewText: 'Your creator details are in review. We will reach out with next steps.',
    heading: "You're on the list. We'll take it from here.",
    body: [
      'Thanks for applying to Raptive Community. Your application now includes the creator identity, discovered channels, brand preview, and verification details you confirmed.',
      'Our team will review brand fit, audience signals, and community readiness.',
      'If there is a match, we will follow up with the next step for setting up your community space.',
    ],
    primaryAction: {
      label: 'View application status',
      href: 'https://community-ds.vercel.app/community-ds/?view=creator-application-page',
    },
    secondaryNote: 'Most reviews start with the details you already confirmed, so there is no long form to repeat.',
  },
  {
    id: 'needs-info',
    label: 'Needs info',
    tone: 'Action needed',
    status: 'Sent when review needs a correction or missing signal',
    subject: 'One more detail for your Raptive Community application',
    previewText: 'We need a confirmed creator channel before your application can continue.',
    heading: 'We need one more creator signal.',
    body: [
      'We could not confidently confirm the creator presence connected to your application.',
      'Please add at least one active website or social channel and complete verification for that channel.',
      'Once that is done, your application can continue through review without starting over.',
    ],
    primaryAction: {
      label: 'Add creator channel',
      href: 'https://community-ds.vercel.app/community-ds/?view=creator-application-page',
    },
    secondaryNote: 'Accepted channels include website, Instagram, TikTok, YouTube, and Facebook.',
  },
  {
    id: 'approved-next-steps',
    label: 'Approved',
    tone: 'Next step',
    status: 'Sent after admin approval',
    subject: 'Your Raptive Community application was approved',
    previewText: 'You are approved to continue setup and prepare your community invitation path.',
    heading: 'You are approved to keep building.',
    body: [
      'Good news: Culture Crave is approved to continue with Raptive Community setup.',
      'The preview you reviewed during application will help us start from your brand, audience, and community direction.',
      'Next, we will help you confirm setup details, refine the first member experience, and prepare your invitation plan.',
    ],
    primaryAction: {
      label: 'Continue setup',
      href: 'https://community-ds.vercel.app/community-ds/?view=creator-application-page',
    },
    secondaryNote: 'Approval is the start of setup. Your community opens after final readiness details are confirmed.',
  },
  {
    id: 'not-a-fit',
    label: 'Not a fit',
    tone: 'Decision',
    status: 'Sent after admin rejection',
    subject: 'An update on your Raptive Community application',
    previewText: 'We reviewed your application and are not able to move forward right now.',
    heading: 'Thank you for applying.',
    body: [
      'We reviewed your creator profile, audience signals, and community fit for Raptive Community.',
      'We are not able to move forward with this application right now.',
      'We appreciate the time you spent sharing your creator presence with us and hope to make Community available to more creators over time.',
    ],
    primaryAction: {
      label: 'Visit Raptive',
      href: 'https://raptive.com/community/creators/',
    },
    secondaryNote: 'This does not affect other Raptive products or relationships you may have.',
  },
]
